// Refinamento Final V3 — conteúdo consolidado e ampliado.

export const maxillariaPicta = {
    "id": "maxillaria-picta",
    "nome": "Maxillaria picta",
    "genero": "Maxillaria",
    "tipo": "Espécie botânica",
    "dificuldade": "Moderada",
    "caracteristicas": ["Epífita ou litófita", "Flores claras pintalgadas", "Pseudobulbos bifoliados", "Flores basais de textura cerosa", "Forma touceiras densas"],
    "fotos": ["imagens/Maxillaria picta/Maxillaria picta1.webp", "imagens/Maxillaria picta/Maxillaria picta2.jpeg", "imagens/Maxillaria picta/Maxillaria picta3.jpg", "imagens/Maxillaria picta/Maxillaria picta4.jpg"],
    "descricao": "Espécie simpodial brasileira de porte pequeno a médio, com pseudobulbos ovoides, frequentemente sulcados quando maduros, sustentando normalmente duas folhas apicais coriáceas. As flores solitárias surgem em hastes curtas na base dos pseudobulbos e apresentam fundo creme, amarelo ou alaranjado-claro com manchas castanhas ou púrpuras. O epíteto picta significa ‘pintada’, referência direta à padronagem característica. Em touceiras maduras, a floração pode ser numerosa e produzir forte efeito ornamental.",
    "origem": "Nativa do Sudeste e Sul do Brasil, estendendo-se até Misiones, na Argentina. Ocorre em diferentes formações da Mata Atlântica, incluindo ambientes sazonais e matas de altitude, o que explica sua preferência por boa luminosidade filtrada, ventilação e noites moderadamente frescas.",
    "regiao": "Sudeste e Sul do Brasil até Misiones, Argentina.",
    "habitat": "Epífita ou litófita sobre troncos, galhos e rochas bem drenadas, em ambientes claros, ventilados e sujeitos a variação sazonal de temperatura e umidade. Recebe água regularmente durante o crescimento, mas as raízes não permanecem em material saturado e sem ar.",
    "clima": "Intermediário a fresco, com melhor desempenho aproximado entre 18°C e 28°C, umidade de 60% a 85% e circulação de ar constante. Pode tolerar quedas breves para cerca de 8°C a 10°C quando seca e protegida, mas não deve ser exposta a geada. Acima de 32°C, precisa de sombra térmica, boa ventilação e vaso que não aqueça excessivamente.",
    "climaFloracao": "A floração depende de pseudobulbos completamente maduros, luz suficiente e raízes ativas. A queda moderada da temperatura noturna no outono e inverno pode atuar como estímulo, mas não substitui o amadurecimento adequado nem significa necessidade de frio extremo. Excesso de nitrogênio, sombra profunda ou divisão recente favorecem crescimento vegetativo em detrimento das flores.",
    "iluminacao": {"sombrite": "50% a 60% como referência", "solDireto": "Somente muito suave e após aclimatação", "horario": "Primeiras horas da manhã, conforme intensidade local", "observacoes": "Forneça luz filtrada brilhante. Folhas muito escuras, pseudobulbos alongados e pouca floração indicam sombra excessiva; amarelecimento rápido e lesões secas indicam excesso de luz ou calor. Aumentos de luminosidade devem ser graduais."},
    "floracao": "Mais comum do inverno ao início da primavera, normalmente entre julho e outubro, com variações relacionadas à altitude, procedência e manejo. As flores são solitárias, cerosas e relativamente duráveis. Hastes sucessivas podem surgir de diferentes pseudobulbos maduros, dando aparência de floração abundante. O perfume costuma ser discreto e pode variar entre exemplares, temperatura e horário.",
    "adubacao": "🌿 Orgânica: bokashi em pequena quantidade, dentro de porta-adubo na borda do vaso e afastado do rizoma.\n💧 Foliar/mineral: NPK equilibrado em 1/4 a 1/3 da dose a cada 10–15 dias durante emissão de brotos e raízes, aplicado sobre raízes previamente molhadas. Reduza após o amadurecimento.\n🧪 Liberação lenta: poucos grânulos de Osmocote, Basacote ou equivalente podem ser usados em vasos muito drenantes. Evite excesso de nitrogênio e faça lavagens periódicas com água limpa para retirar sais.",
    "rega": "Durante a brotação, mantenha o substrato fresco com regas abundantes e secagem parcial entre elas. Após a maturação dos pseudobulbos, amplie ligeiramente o intervalo, especialmente em semanas frias e nubladas, sem impor seca total. Pseudobulbos levemente sulcados podem ser naturais; enrugamento profundo com raízes escuras e substrato molhado indica perda radicular, não simples falta de água.",
    "suporte": "🥇 Vaso de barro ou plástico baixo e bem perfurado, apenas ligeiramente maior que a touceira.\n🥈 Cachepô ou cesto de madeira para exemplares adultos e ambientes com umidade suficiente.\n🥉 Placa com fina camada de musgo apenas em orquidários úmidos e com regas frequentes. Replante exclusivamente no início da emissão de raízes novas e evite divisões pequenas; pseudobulbos antigos verdes devem permanecer como reserva.",
    "substrato": "Mistura principal: casca de pinus pequena a média + pedra-pomes + carvão vegetal. Alternativa: casca de pinus + brita fina + pequena quantidade de esfagno solto. Para Serra/ES, pedra-pomes, casca de pinus, carvão e uma pequena proporção de akadama proporcionam bom equilíbrio. Fibra de coco em cubos só deve ser usada se estiver bem lavada, estabilizada e sem compactação.",
    "errosComuns": "Replantar fora do início das raízes; usar vaso grande; enterrar o rizoma; manter substrato constantemente saturado no frio; cultivar em sombra profunda; excesso de nitrogênio; cortar pseudobulbos antigos ainda verdes; dividir excessivamente a touceira. Cochonilhas podem esconder-se nas bainhas, lesmas atacam botões basais e manchas negras de expansão rápida exigem isolamento e correção do abafamento.",
    "dica": "O sucesso depende de três cuidados combinados: replante apenas quando surgirem raízes novas; permita noites mais frescas após a maturação dos pseudobulbos; e inspecione a base da touceira. Retire somente bainhas completamente secas e soltas, com a planta seca e sem forçar tecidos aderidos, para não ferir brotos nem botões basais.",
    "adaptacaoRegional": {"litoralQuente": "Em Serra/ES, use vaso pequeno, mistura mais mineral, ventilação contínua e proteção contra calor abafado. Favoreça alguma amplitude térmica natural e evite aquecimento do vaso durante o verão.", "montanhaFrio": "Geralmente adapta-se muito bem. Nas semanas frias e chuvosas, reduza a frequência das regas, mantendo raízes ativas levemente úmidas, e proteja de geadas."},
    "mesesFloracao": [7, 8, 9, 10],
    "avaliacoes": {"cultivo": 3, "floracao": 3, "perfume": 2, "luminosidade": 3, "agua": 4, "raridade": 4}
};
