// Pinalia elata — dados taxonômicos documentados; cultivo inferido do habitat montano.
// ALERTA: imagens da internet frequentemente representam outras espécies; não inserir sem validação.
export const pinaliaElata = {
 id:"pinalia-elata", nome:"Pinalia elata", genero:"Pinalia", tipo:"Espécie botânica",
 sinonimo:"Eria elata Hook.f.", dificuldade:"Difícil",
 origem:"Malásia peninsular", regiao:"Montanhas da península da Malásia",
 habitat:"Epífita de florestas montanas úmidas, incluindo floresta nebular; material documentado a aproximadamente 1.700 m em Ulu Kali.",
 descricao:"Espécie epífita simpodial de florestas montanas úmidas da Malásia peninsular. Apresenta caules engrossados, folhas apicais e inflorescências eretas. A revisão de Besi et al. (2023) descreve flores relativamente fechadas, espaçadas e acompanhadas por brácteas grandes castanhas ou arroxeadas. Muitas imagens comerciais sob o nome Eria elata mostram flores brancas estreladas abertas, cuja identificação precisa ser reavaliada. A avaliação preliminar de conservação como CR proposta pelos autores não equivale à classificação oficial da IUCN. As receitas de cultivo abaixo são experimentais e derivadas da ecologia, não de ensaios controlados brasileiros.",
 caracteristicas:["Epífita", "Malásia", "Floresta montana", "Flores ~11 × 8 mm", "Inflorescência ~20 cm (estudo de 2023)", "Labelo trilobado", "Brácteas arroxeadas"],
 fotos:[
  "https://upload.wikimedia.org/wikipedia/commons/e/e5/Pinalia_elata.jpg",
  "https://cdnhuawei.lojavirtuolpro.com/orquidariorobertomartins/produto/multifotos/20230105141411_5381994619_DM.webp",
  "https://cdnhuawei.lojavirtuolpro.com/orquidariorobertomartins/produto/20230105141406_5221994779_D.webp",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk4nfIDQ3bgJbSlmIh_5dR90_w4VAf7EFkU4T6tSM1Zg&s",
],
 referenciasFotograficas:["https://www.orchidspecies.com/eriaelata.htm","https://www.scielo.sa.cr/scielo.php?pid=S1409-38712023000200145&script=sci_arttext","https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:651507-1/images"],
 selosCultivo:{rega:{nivel:"frequente"},climaFloracao:{faixa:"frio"}},
 avaliacoes:{cultivo:2,floracao:2,perfume:1,luminosidade:2,agua:4,raridade:5},
 mesesFloracao:[], clima:"Fresco a frio, úmido e ventilado; sensível a noites persistentemente quentes.",
 climaFloracao:"Priorizar noites frescas, umidade atmosférica alta e ar renovado. Como referência experimental, testar noites de 12–18 °C e dias de 18–25 °C, sem tratar essas faixas como limites comprovados para a espécie. Em Serra/ES, o calor noturno é o principal entrave, mesmo sob sombra. Em Santa Teresa/ES, escolher o ponto mais fresco e protegido de vento ressecante. Não tentar compensar temperaturas inadequadas com regas excessivas ou adubo de floração.",
 iluminacao:{sombrite:"70–80% (ponto de partida experimental)",solDireto:"Não permitido",horario:"Somente início da manhã, se muito suave",observacoes:"Sombra luminosa de floresta montana. A porcentagem é uma estimativa de manejo, não uma medição publicada para esta espécie. Observe aquecimento das folhas e alongamento excessivo."},
 floracao:"Besi et al. (2023) documentaram floração em outubro e novembro na Malásia: inflorescências eretas, brácteas grandes e flores relativamente fechadas. Esses meses não são calendário confirmado para o Espírito Santo. Registrar brotação, início da haste e abertura floral por dois ciclos; fotografar labelo e brácteas para validar a identificação. Crescimento vegetativo sem flores pode indicar noites quentes ou luz insuficiente.",
 adubacao:"🌱 Orgânica: bokashi em dose mínima e afastado de brotos e raízes, somente no crescimento ativo.\n💧 Mineral/foliar: NPK equilibrado, por exemplo 20-20-20, a 1/4 da dose do fabricante a cada 14–15 dias durante emissão de brotos e raízes.\n🧪 Após maturação: espaçar para 20–30 dias ou suspender se a planta estiver parada. Lavar o vaso com água limpa periodicamente para reduzir sais. Não usar fósforo concentrado para tentar corrigir noites quentes. Orientação conservadora, não ensaio específico.",
 rega:"Molhar pela manhã até a água atravessar todo o vaso e escorrer. Regar novamente quando a superfície começar a secar, mantendo leve umidade no interior sem saturação. Em crescimento ativo, observar raízes novas e peso do vaso diariamente; no frio, espaçar conforme a secagem real. Evitar tanto desidratação prolongada quanto esfagno compacto e molhado durante a noite. Não impor repouso totalmente seco sem evidência de dormência.",
 suporte:["🥇 Vaso plástico vasado proporcional à touceira, com furos laterais e substrato granuloso.","🥈 Cesto de madeira ou plástico ripado com casca média e pequena reserva de esfagno solto.","🥉 Placa de cortiça ou tronco rugoso com esfagno mínimo, apenas em orquidário de alta umidade e regas frequentes."],
 formasCultivo:{perfilVisual:"epifita-pseudobulbosa",destaque:"Vaso plástico vasado",resumo:"A foto enviada ilustra um vaso ripado com casca grossa e excelente drenagem. Ela serve como referência de montagem, mas não confirma a identificação da verdadeira Pinalia elata.",metodos:[
{nome:"Vaso plástico vasado",asset:"pinalia-elata-vaso-vasado",estrelas:5,status:"Ideal",texto:"Vaso pequeno com aberturas laterais: boa oxigenação e retenção moderada. Evitar aquecimento por sol direto."},
{nome:"Cesto de madeira",asset:"cesto-madeira",estrelas:4,status:"Muito recomendado",texto:"Drenagem e ventilação excelentes, porém exige atenção maior à secagem e à umidade ambiente."},
{nome:"Placa / tronco",asset:"placa-madeira",estrelas:3,status:"Alternativa",texto:"Somente onde raízes expostas possam receber umidade regular sem permanecer abafadas."}]},
 substrato:["40% casca de pinus média + 25% pedra-pomes + 20% esfagno fibroso solto + 15% carvão vegetal médio.","40% casca de macadâmia média + 30% pinus médio + 20% pedra-pomes + 10% esfagno solto.","45% pinus médio + 30% carvão médio + 15% pedra-pomes + 10% esfagno solto para locais muito úmidos."],
 substratoVisual:{titulo:"Substrato ideal",contexto:"Receita experimental para vaso plástico vasado",resumo:"Mistura aberta, de granulometria média, com alta aeração e retenção moderada; não há fórmula validada para a espécie.",justificativa:"A ecologia epífita montana favorece raízes arejadas com umidade atmosférica constante. Pinus mantém estrutura, pedra-pomes estabiliza e retém alguma água, esfagno solto reduz ressecamento e carvão preserva macroporos. A foto enviada exemplifica o vaso ripado, mas não comprova a identidade botânica da planta.",receitaTexto:"40% casca de pinus média + 25% pedra-pomes (4–8 mm) + 20% esfagno fibroso solto + 15% carvão vegetal médio.",perfil:["Epífita montana","Aeração muito alta","Umidade moderada","Secagem gradual","Baixa compactação"],comportamento:{retencao:3,aeracao:5,secagem:3,compactacao:1},itens:[
{asset:"casca-pinus",nome:"Casca de pinus média",proporcao:"40%",nota:"estrutura",finalidade:"Mantém espaços de ar e reserva hídrica moderada; renovar ao decompor."},
{asset:"pedra-pomes",nome:"Pedra-pomes 4–8 mm",proporcao:"25%",nota:"mineral poroso",finalidade:"Aumenta estabilidade, drenagem e reserva moderada de água."},
{asset:"esfagno",nome:"Esfagno fibroso solto",proporcao:"20%",nota:"umidade",finalidade:"Suaviza a secagem; distribuir sem compactar ou cobrir os brotos."},
{asset:"carvao-vegetal",nome:"Carvão vegetal médio",proporcao:"15%",nota:"aeração",finalidade:"Preserva macroporos e reduz adensamento."}
],alerta:"Ajustar esfagno para 10% em ambiente muito úmido; nunca deixar água acumulada no cachepô. Furos desobstruídos são mais importantes que uma camada grossa de brita."},
 errosComuns:["Identificar apenas pela cor branca ou por flores estreladas abertas.","Usar terra vegetal ou esfagno compactado no vaso.","Superdimensionar o vaso, mantendo o centro encharcado.","Regar à noite em local quente e sem ventilação.","Expor a sol forte para estimular floração.","Impor repouso seco sem comprovação.","Aplicar bokashi sobre brotos ou NPK muito concentrado.","Confundir alta umidade do ar com substrato sempre saturado."],
 revisaoCientificaIAR:{nome:"Pinalia elata",statusTaxonomico:"Nome aceito por POWO/Kew.",sinonimosPrincipais:"Eria elata Hook.f.",morfologiaDimensoes:"Flores de aproximadamente 11 × 8 mm; inflorescências ~20 cm no material revisado em 2023; brácteas conspícuas e ápice do labelo trilobado.",habitatAltitudeClima:"Floresta nebular montana malaia, entre 1.600 e 1.800 m; exemplar documentado a cerca de 1.700 m.",distribuicaoGeografica:"Endêmica da Malásia peninsular.",cultivoPremiacao:"Manejo inferido do habitat; sem confirmação suficiente de protocolos específicos de produtores brasileiros.",confianca:"moderada para ecologia, baixa para cultivo brasileiro",fontes:["POWO/Kew","IOSPE","Besi et al., Lankesteriana 2023"]},
 indiceDificuldadeCultivo:{versao:"IDC 3.2 — estimativa ecológica",escala:"dificuldade",indice:71,classificacao:"Difícil",cultivoEstrelas:2,criterios:{temperatura:{notaDificuldade:5,peso:15},rega:{notaDificuldade:3,peso:15},umidade:{notaDificuldade:4,peso:10},ventilacao:{notaDificuldade:3,peso:10},luminosidade:{notaDificuldade:2,peso:10},raizesSubstrato:{notaDificuldade:3,peso:10},sazonalidade:{notaDificuldade:3,peso:10},floracao:{notaDificuldade:4,peso:20}},faixas:{facil:"0–25",moderada:"26–50",dificil:"51–89",extrema:"90–100"}},
 indiceAdaptacaoRegional:{versao:"IAR 2.0 — estimativa ecológica",escala:"compatibilidade regional",metodo:"Pontuação exploratória; dados de cultivo brasileiro específico insuficientes",litoralQuente:{indice:28,estrelas:2,fatores:{habitatNatural:{nota:1,peso:30},temperatura:{nota:1,peso:30},aguaUmidade:{nota:3,peso:5},ventilacao:{nota:3,peso:5},luminosidade:{nota:4,peso:5},sazonalidade:{nota:2,peso:5},floracao:{nota:1,peso:20}}},montanhaFrio:{indice:77,estrelas:4,fatores:{habitatNatural:{nota:4,peso:30},temperatura:{nota:4,peso:30},aguaUmidade:{nota:4,peso:5},ventilacao:{nota:4,peso:5},luminosidade:{nota:4,peso:5},sazonalidade:{nota:3,peso:5},floracao:{nota:3,peso:20}}}},
 adaptacaoRegional:{tituloMontanha:"Montanha com noites frescas",litoral:{texto:"Baixa compatibilidade térmica prevista: o calor noturno do litoral é o principal limitante; ventilação e sombra não substituem noites frescas."},montanha:{texto:"Mais promissora em local fresco e úmido, mas a altitude da origem e a ausência de experiências locais recomendam cautela."}},
 dica:"🏆 A chave para diferenciar a verdadeira Pinalia elata é observar as flores ainda fechadas, com brácteas grandes arroxeadas e uma pequena porção avermelhada do labelo visível; não espere que elas se abram como estrelas brancas. Para cultivar, priorize noites frescas e umidade atmosférica contínua, sem encharcar as raízes."
};
