// Pinalia elata — dados taxonômicos documentados; cultivo inferido do habitat montano.
// ALERTA: imagens da internet frequentemente representam outras espécies; não inserir sem validação.
export const pinaliaElata = {
 id:"pinalia-elata", nome:"Pinalia elata", genero:"Pinalia", tipo:"Espécie botânica",
 sinonimo:"Eria elata Hook.f.", dificuldade:"Difícil",
 origem:"Malásia peninsular", regiao:"Montanhas da península da Malásia",
 habitat:"Epífita de florestas montanas úmidas, incluindo floresta nebular; material documentado a aproximadamente 1.700 m em Ulu Kali.",
 descricao:"Espécie epífita com caules carnosos e folhas apicais. As inflorescências eretas apresentam 5–6 flores fechadas e espaçadas na metade superior, com brácteas grandes, arroxeadas ou castanhas. Na verdadeira Pinalia elata, as flores ficam relativamente fechadas, lembrando botões; o ápice do labelo é trilobado. Fotografias de flores brancas amplamente estreladas publicadas como Eria elata podem corresponder a outra espécie. O estudo de 2023 propõe avaliação preliminar como criticamente ameaçada (CR); não confundir essa proposta com uma classificação oficial publicada na Lista Vermelha da IUCN.",
 caracteristicas:["Epífita", "Malásia", "Floresta montana", "Flores ~11 × 8 mm", "Inflorescência ~20 cm (estudo de 2023)", "Labelo trilobado", "Brácteas arroxeadas"],
 fotos:[
  "https://upload.wikimedia.org/wikipedia/commons/e/e5/Pinalia_elata.jpg",
  "https://cdnhuawei.lojavirtuolpro.com/orquidariorobertomartins/produto/multifotos/20230105141411_5381994619_DM.webp",
  "https://cdnhuawei.lojavirtuolpro.com/orquidariorobertomartins/produto/20230105141406_5221994779_D.webp",
  "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRk4nfIDQ3bgJbSlmIh_5dR90_w4VAf7EFkU4T6tSM1Zg&s",
],
 referenciasFotograficas:["https://www.orchidspecies.com/eriaelata.htm","https://www.scielo.sa.cr/scielo.php?pid=S1409-38712023000200145&script=sci_arttext","https://powo.science.kew.org/taxon/urn:lsid:ipni.org:names:651507-1/images"],
 selosCultivo:{rega:{nivel:"frequente"},climaFloracao:{faixa:"frio"}},
 avaliacoes:{cultivo:2,floracao:2,perfume:1,luminosidade:2,agua:4,raridade:5},
 mesesFloracao:[], clima:"Fresco a frio, úmido e ventilado; sensível a noites persistentemente quentes.",
 climaFloracao:"O habitat documentado entre 1.600 e 1.800 m, com neblina frequente, sugere a importância de noites frescas e umidade atmosférica elevada. Não há evidência suficiente para prometer floração regular no litoral quente da Serra/ES. Em Santa Teresa, priorize o ponto mais fresco, com ar renovado e sem ressecamento prolongado.",
 iluminacao:{sombrite:"70–80% (ponto de partida experimental)",solDireto:"Não permitido",horario:"Somente início da manhã, se muito suave",observacoes:"Sombra luminosa de floresta montana. A porcentagem é uma estimativa de manejo, não uma medição publicada para esta espécie. Observe aquecimento das folhas e alongamento excessivo."},
 floracao:"Inflorescências axilares eretas, com várias flores fechadas e espaçadas e brácteas conspícuas. Na natureza, o estudo de Besi et al. (2023) registrou floração principalmente em outubro e novembro. Não há dados suficientes para transpor esses meses ao cultivo brasileiro.",
 adubacao:"Durante brotação e enraizamento ativos, usar fertilizante equilibrado em cerca de 1/4 da dose do fabricante a cada 15 dias; lavar periodicamente com água limpa. Bokashi, se usado, deve ficar afastado das raízes. Reduzir adubação quando o crescimento desacelerar. Trata-se de orientação conservadora inferida do hábito epífito, não de ensaio específico.",
 rega:"Molhar abundantemente durante crescimento ativo, deixando drenar por completo. Evitar tanto a secagem prolongada de raízes ativas quanto a saturação contínua, sobretudo sob temperaturas altas. Em clima frio, reduzir a frequência conforme a velocidade real de secagem, sem impor repouso seco não documentado.",
 suporte:["Vaso pequeno e muito ventilado com substrato aberto e alguma reserva hídrica.","Cesto de madeira com casca e esfagno solto, em ambiente de umidade elevada.","Placa de cortiça ou madeira com esfagno mínimo, somente onde a umidade puder ser mantida."],
 formasCultivo:{perfilVisual:"epifita-pseudobulbosa",destaque:"Vaso plástico vasado",resumo:"Preferir umidade estável com raízes oxigenadas; a escolha do suporte é inferida da ecologia montana e ainda carece de ensaios brasileiros específicos.",metodos:[
 {nome:"Vaso plástico vasado",asset:"vaso-plastico-vasado",estrelas:5,status:"Ideal",texto:"Permite equilibrar retenção e drenagem com controle mais fácil em ambiente fresco."},
 {nome:"Cesto de madeira",asset:"cesto-madeira",estrelas:4,status:"Muito recomendado",texto:"Oferece ventilação lateral; requer regas ajustadas para não ressecar."},
 {nome:"Placa / tronco",asset:"placa-madeira",estrelas:3,status:"Alternativa",texto:"Exige umidade atmosférica constante e regas mais frequentes; não recomendada em ar seco."}]},
 substrato:["Casca de pinus média + esfagno solto + carvão vegetal", "Casca de pinus média + pedra-pomes + esfagno solto"],
 substratoVisual:{titulo:"Substrato sugerido",contexto:"Receita experimental para vaso ventilado",resumo:"Estrutura aberta com retenção moderada; não há formulação validada especificamente para Pinalia elata.",receitaTexto:"50% casca de pinus média + 25% pedra-pomes + 15% esfagno solto + 10% carvão vegetal.",perfil:["Epífita montana","Aeração alta","Umidade moderada a alta"],comportamento:[{nome:"Retenção",valor:3,icone:"💧"},{nome:"Aeração",valor:4,icone:"💨"},{nome:"Secagem",valor:3,icone:"⚡"},{nome:"Compactação",valor:1,icone:"🧱"}],itens:[],alerta:"Evitar calor excessivo na zona radicular e substrato permanentemente saturado."},
 errosComuns:["Identificar a planta apenas por fotos de flores brancas abertas.","Expor ao sol forte.","Confundir umidade alta com substrato encharcado.","Deixar noites quentes e abafadas sem circulação de ar.","Atribuir meses de floração sem dados observacionais."],
 revisaoCientificaIAR:{nome:"Pinalia elata",statusTaxonomico:"Nome aceito por POWO/Kew.",sinonimosPrincipais:"Eria elata Hook.f.",morfologiaDimensoes:"Flores de aproximadamente 11 × 8 mm; inflorescências ~20 cm no material revisado em 2023; brácteas conspícuas e ápice do labelo trilobado.",habitatAltitudeClima:"Floresta nebular montana malaia, entre 1.600 e 1.800 m; exemplar documentado a cerca de 1.700 m.",distribuicaoGeografica:"Endêmica da Malásia peninsular.",cultivoPremiacao:"Manejo inferido do habitat; sem confirmação suficiente de protocolos específicos de produtores brasileiros.",confianca:"moderada para ecologia, baixa para cultivo brasileiro",fontes:["POWO/Kew","IOSPE","Besi et al., Lankesteriana 2023"]},
 indiceDificuldadeCultivo:{versao:"IDC 3.2 — estimativa ecológica",escala:"dificuldade",indice:71,classificacao:"Difícil",cultivoEstrelas:2,criterios:{temperatura:{notaDificuldade:5,peso:15},rega:{notaDificuldade:3,peso:15},umidade:{notaDificuldade:4,peso:10},ventilacao:{notaDificuldade:3,peso:10},luminosidade:{notaDificuldade:2,peso:10},raizesSubstrato:{notaDificuldade:3,peso:10},sazonalidade:{notaDificuldade:3,peso:10},floracao:{notaDificuldade:4,peso:20}},faixas:{facil:"0–25",moderada:"26–50",dificil:"51–89",extrema:"90–100"}},
 indiceAdaptacaoRegional:{versao:"IAR 2.0 — estimativa ecológica",escala:"compatibilidade regional",metodo:"Pontuação exploratória; dados de cultivo brasileiro específico insuficientes",litoralQuente:{indice:28,estrelas:2,fatores:{habitatNatural:{nota:1,peso:30},temperatura:{nota:1,peso:30},aguaUmidade:{nota:3,peso:5},ventilacao:{nota:3,peso:5},luminosidade:{nota:4,peso:5},sazonalidade:{nota:2,peso:5},floracao:{nota:1,peso:20}}},montanhaFrio:{indice:77,estrelas:4,fatores:{habitatNatural:{nota:4,peso:30},temperatura:{nota:4,peso:30},aguaUmidade:{nota:4,peso:5},ventilacao:{nota:4,peso:5},luminosidade:{nota:4,peso:5},sazonalidade:{nota:3,peso:5},floracao:{nota:3,peso:20}}}},
 adaptacaoRegional:{tituloMontanha:"Montanha com noites frescas",litoral:{texto:"Baixa compatibilidade térmica prevista: o calor noturno do litoral é o principal limitante; ventilação e sombra não substituem noites frescas."},montanha:{texto:"Mais promissora em local fresco e úmido, mas a altitude da origem e a ausência de experiências locais recomendam cautela."}},
 dica:"🏆 A chave para diferenciar a verdadeira Pinalia elata é observar as flores ainda fechadas, com brácteas grandes arroxeadas e uma pequena porção avermelhada do labelo visível; não espere que elas se abram como estrelas brancas. Para cultivar, priorize noites frescas e umidade atmosférica contínua, sem encharcar as raízes."
};
